# Tek sunucu: React build + FastAPI (port 8000)
FROM node:22-alpine AS frontend
WORKDIR /app/frontend
COPY frontend/package.json frontend/yarn.lock ./
RUN yarn install --frozen-lockfile
COPY frontend/ ./

# Dokploy → Build-time Arguments (docker --build-arg)
ARG REACT_APP_SUPABASE_URL
ARG REACT_APP_SUPABASE_ANON_KEY
ARG REACT_APP_DID_API_KEY
ARG REACT_APP_DID_ENABLED=false
ARG REACT_APP_AVATAR_PROVIDER=mp4
ARG REACT_APP_WAV2LIP_ENABLED=false
ARG REACT_APP_LESSON_IDLE_VIDEO=/video2.mp4
ARG REACT_APP_LESSON_SPEAKING_VIDEO=/video3.mp4
ARG REACT_APP_LESSON_WELCOME_VIDEO=/merhaba.mp4

# CRA sadece build aninda .env* okur — ARG'lari dosyaya yaz
RUN set -e; \
  if [ -z "$REACT_APP_SUPABASE_URL" ] || [ -z "$REACT_APP_SUPABASE_ANON_KEY" ]; then \
    echo "ERROR: REACT_APP_SUPABASE_URL ve REACT_APP_SUPABASE_ANON_KEY build-arg zorunlu"; \
    exit 1; \
  fi; \
  printf '%s\n' \
    "REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}" \
    "REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}" \
    "REACT_APP_DID_API_KEY=${REACT_APP_DID_API_KEY}" \
    "REACT_APP_DID_ENABLED=${REACT_APP_DID_ENABLED}" \
    "REACT_APP_AVATAR_PROVIDER=${REACT_APP_AVATAR_PROVIDER}" \
    "REACT_APP_WAV2LIP_ENABLED=${REACT_APP_WAV2LIP_ENABLED}" \
    "REACT_APP_LESSON_IDLE_VIDEO=${REACT_APP_LESSON_IDLE_VIDEO}" \
    "REACT_APP_LESSON_SPEAKING_VIDEO=${REACT_APP_LESSON_SPEAKING_VIDEO}" \
    "REACT_APP_LESSON_WELCOME_VIDEO=${REACT_APP_LESSON_WELCOME_VIDEO}" \
    "REACT_APP_BACKEND_URL=" \
    > .env.production; \
  echo "=== Build env (URL only) ==="; \
  grep REACT_APP_SUPABASE_URL .env.production

ENV REACT_APP_SUPABASE_URL=$REACT_APP_SUPABASE_URL
ENV REACT_APP_SUPABASE_ANON_KEY=$REACT_APP_SUPABASE_ANON_KEY
ENV REACT_APP_DID_API_KEY=$REACT_APP_DID_API_KEY
ENV REACT_APP_DID_ENABLED=$REACT_APP_DID_ENABLED
ENV REACT_APP_AVATAR_PROVIDER=$REACT_APP_AVATAR_PROVIDER
ENV REACT_APP_WAV2LIP_ENABLED=$REACT_APP_WAV2LIP_ENABLED
ENV REACT_APP_LESSON_IDLE_VIDEO=$REACT_APP_LESSON_IDLE_VIDEO
ENV REACT_APP_LESSON_SPEAKING_VIDEO=$REACT_APP_LESSON_SPEAKING_VIDEO
ENV REACT_APP_LESSON_WELCOME_VIDEO=$REACT_APP_LESSON_WELCOME_VIDEO
ENV REACT_APP_BACKEND_URL=

RUN yarn build

FROM python:3.12-slim-bookworm
WORKDIR /app/backend
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libffi-dev \
    && rm -rf /var/lib/apt/lists/*
COPY backend/requirements-deploy.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ ./
COPY --from=frontend /app/frontend/build /app/frontend/build
ENV FRONTEND_BUILD_PATH=/app/frontend/build
ENV PYTHONUNBUFFERED=1
EXPOSE 8000
CMD ["uvicorn", "ai_server:app", "--host", "0.0.0.0", "--port", "8000"]
